### ISSUE TITLE
Doesn't respond properly on smaller screens

### ISSUE THREAD

**Issue by Reillyhewitson** [XFour-IT/www.xfour.co.uk#6]
Issues with proper CSS on new iPad pro. Might have to look into adjusting it with JavaScript.

**Comment by Reillyhewitson** [comment]
Possible fix on #5 will need to be checked

**Comment by Reillyhewitson** [comment]
Just some cosmetic issues now.

**Comment by benjisoft** [comment]
Issue fixed in redesign
